apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hub.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
  - port: {{ .Values.hub.service.port }}
    targetPort: 8888
    protocol: TCP
    name: http
  {{- if .Values.dev.hub.debug }}
  - port: 15678
    targetPort: 5678
    protocol: TCP
    name: debugpy
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub
