{{- if .Values.notebook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.notebook.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: notebook
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
