apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- if .Values.secrets.cognitoClientId | default false }}
  COGNITO_CLIENT_ID: {{ .Values.secrets.cognitoClientId | quote }}
  {{- end }}
  {{- if .Values.secrets.cognitoUserPoolId }}
  COGNITO_CLIENT_USER_POOL_ID: {{ .Values.secrets.cognitoUserPoolId | quote }}
  {{- end }}
  {{- if .Values.secrets.cognitoAwsRegion }}
  COGNITO_AWS_REGION: {{ .Values.secrets.cognitoAwsRegion | quote }}
  {{- end }}
  {{- if .Values.secrets.cognitoClientSecret }}
  COGNITO_CLIENT_SECRET: {{ .Values.secrets.cognitoClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.vaultEncryptionKey }}
  BEAKERHUB_VAULT_KEY: {{ .Values.secrets.vaultEncryptionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKeys }}
  {{- range $key, $value := .Values.secrets.apiKeys }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  CONFIGPROXY_AUTH_TOKEN: {{ .Values.secrets.configProxyAuthToken | default (lookup "v1" "Secret" .Values.namespace "proxy-secrets" | dig "data" "CONFIGPROXY_AUTH_TOKEN" "" | b64dec) | default (randAlphaNum 18) | quote }}

{{- range $key, $value := .Values.secrets.envByNode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}-secrets
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
stringData:
  {{- toYaml $value | nindent 2 }}
{{- end }}
