---
# Automatically build and publish

name: Build and Publish

# yamllint disable-line rule:truthy
on:
  push:
    tags: ['v[0-9]+**']
  workflow_dispatch:

jobs:
    build-python:
        name: Build & Publish
        runs-on: ubuntu-22.04
        env:
          UV_PRERELEASE: allow
          PIP_PRE: 1
        permissions:
            id-token: write
        steps:
            - name: Apt update and build install
              shell: bash
              run: |
                  sudo apt update || true
                  sudo apt install -y nodejs npm python3-pip || true
                  pip install uv hatch

            - name: Checkout
              uses: actions/checkout@v5
              with:
                ref: ${{ github.event.workflow_run.head_branch }}

            - name: make build
              shell: bash
              run: |
                  make build

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
